### ISSUE TITLE
Error on `node app.js`

### ISSUE THREAD

**Issue by dzhuang** [XimeraProject/server#59]
```
root@(none):~/course/ximera-trial/ximera# node app.js
info: Initializing Mongo
/template/3f4797466290bd0d8858132419eec925f94c219f/test
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

/root/course/ximera-trial/ximera/node_modules/connect-mongo/lib/connect-mongo.js:164
        throw new Error('Required MongoStore option `db` missing or is not a s
              ^
Error: Required MongoStore option `db` missing or is not a string.
    at buildUrlFromOptions (/root/course/ximera-trial/ximera/node_modules/connect-mongo/lib/connect-mongo.js:164:15)
    at new MongoStore (/root/course/ximera-trial/ximera/node_modules/connect-mongo/lib/connect-mongo.js:251:7)
    at /root/course/ximera-trial/ximera/app.js:165:9
    at /root/course/ximera-trial/ximera/node_modules/git-rev/index.js:5:5
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by kisonecat** [comment]
It looks like maybe there is a missing configuration file in your environment?  There are better instructions in the [README.md](https://github.com/XimeraProject/server/blob/master/README.md) now
